# Builder for module headers (generated from the built Qt plugin)
# Uses logos-cpp-generator to introspect the compiled plugin and produce SDK headers.
{ lib, common }:

{
  build = {
    pkgs,
    src,
    config,
    commonArgs,
    logosSdk,
    lib,  # The built module library (plugin derivation)
    # API style for the generated `<Module>` client wrapper:
    #   "qt"  — QString / QStringList / QVariantList / QVariantMap / int / LogosResult
    #   "std" — std::string / std::vector<std::string> / LogosMap / LogosList /
    #           int64_t / StdLogosResult (Qt↔std conversion inlined in the .cpp)
    # Each module is built TWICE (once per style) so consumers can pick the
    # variant matching their own --api-style without re-running the codegen
    # at consume time — the two variants are independent derivations and
    # Nix only realises the ones a downstream actually depends on.
    apiStyle ? "qt",
  }:
  let
    pluginFilename = common.getPluginFilename pkgs config.name;
    libExt = common.getLibExtension pkgs;

  in pkgs.stdenv.mkDerivation {
    pname = "${commonArgs.pname}-headers-${apiStyle}";
    version = commonArgs.version;

    inherit src;
    inherit (commonArgs) meta;

    # We need the generator and the built plugin. logosSdk's
    # `propagatedBuildInputs` only ships OpenSSL / Boost /
    # nlohmann_json — Qt is intentionally excluded (see
    # logos-cpp-sdk/nix/default.nix) so qtbase isn't dragged into our
    # closure here, qtPreHook doesn't fire, and we don't need
    # `wrapQtAppsNoGuiHook` either: the generator binary at
    # `${logosSdk}/bin/logos-cpp-generator` was already wrapped at
    # SDK build time. `dontWrapQtApps = true` is kept as a belt-and-
    # suspenders no-op in case a future change re-introduces qtbase.
    nativeBuildInputs = [ logosSdk ];

    dontWrapQtApps = true;

    # No configure phase needed
    dontConfigure = true;

    buildPhase = ''
      runHook preBuild

      # Create output directory for generated headers
      mkdir -p ./generated_headers

      # Determine platform-specific library extension and find plugin
      PLUGIN_FILE=""
      if [ -f "${lib}/lib/${config.name}_plugin.dylib" ]; then
        PLUGIN_FILE="${lib}/lib/${config.name}_plugin.dylib"
      elif [ -f "${lib}/lib/${config.name}_plugin.so" ]; then
        PLUGIN_FILE="${lib}/lib/${config.name}_plugin.so"
      else
        echo "Error: No ${config.name}_plugin library file found in ${lib}/lib/"
        echo "Contents of ${lib}/lib/:"
        ls -la "${lib}/lib/" 2>/dev/null || echo "Directory does not exist"
        exit 1
      fi

      # Set library path so the plugin can find dependencies when loaded
      ${if pkgs.stdenv.hostPlatform.isDarwin then ''
        export DYLD_LIBRARY_PATH="${lib}/lib:''${DYLD_LIBRARY_PATH:-}"
      '' else ''
        export LD_LIBRARY_PATH="${lib}/lib:''${LD_LIBRARY_PATH:-}"
      ''}

      # Run logos-cpp-generator on the built plugin with --module-only flag
      echo "Running logos-cpp-generator on $PLUGIN_FILE"
      echo "Library path: ${lib}/lib"
      ls -la "${lib}/lib" 2>/dev/null || echo "No lib directory"

      # --events-from: typed `on<EventName>(callback)` accessors on the
      # generated wrapper come from the dep's LIDL sidecar (emitted by
      # buildPlugin.nix's installPhase from `logos_events:` blocks in
      # the impl header). Absent for handcrafted Qt modules — that's
      # fine, we skip the flag in that case.
      EVENTS_FROM_FLAG=""
      if [ -f "${lib}/share/logos/${config.name}.lidl" ]; then
        EVENTS_FROM_FLAG="--events-from ${lib}/share/logos/${config.name}.lidl"
        echo "Using events sidecar: ${lib}/share/logos/${config.name}.lidl"
      fi

      logos-cpp-generator "$PLUGIN_FILE" --output-dir ./generated_headers \
        --module-only --api-style ${apiStyle} $EVENTS_FROM_FLAG || {
        echo "Warning: logos-cpp-generator failed, this may be expected if the module has no public API"
        # Create a marker file to indicate attempt was made
        touch ./generated_headers/.no-api
      }

      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      # Install generated headers
      mkdir -p $out/include

      # Copy all generated files (.h and .cpp) to include/ if they exist.
      # Both are needed: downstream modules #include the _api.cpp files from
      # the umbrella logos_sdk.cpp generated by --general-only.
      gen_count=$(find ./generated_headers -maxdepth 1 \( -name '*.h' -o -name '*.cpp' \) 2>/dev/null | wc -l)
      if [ "$gen_count" -gt 0 ]; then
        echo "Copying generated headers and API files..."
        ls -la ./generated_headers
        find ./generated_headers -maxdepth 1 \( -name '*.h' -o -name '*.cpp' \) -exec cp {} $out/include/ \;
      else
        echo "Warning: No generated headers found, creating empty include directory"
        echo "# No headers generated by logos-cpp-generator" > $out/include/.generated
      fi

      runHook postInstall
    '';
  };
}
