# Builder for the module library (Qt plugin .so/.dylib)
# This is the Qt-specific implementation of the plugin build step.
{ lib, common }:

{
  build = {
    pkgs,
    src,
    config,
    commonArgs,
    logosSdk,
    moduleDeps ? {},
    externalLibs ? {},
    preConfigure ? "",
    postInstall ? "",
  }:
  let
    pluginFilename = common.getPluginFilename pkgs config.name;
    libExt = common.getLibExtension pkgs;

    # Collect include directories from module dependencies
    moduleDepIncludes = lib.concatMapStringsSep "\n" (name:
      let dep = moduleDeps.${name} or null;
      in if dep != null then ''
        if [ -d "${dep}/include" ]; then
          echo "Copying include files from ${name}..."
          cp -r "${dep}/include"/* ./generated_code/ 2>/dev/null || true
        fi
      '' else ""
    ) config.dependencies;

    # Copy external libraries to lib/
    externalLibCopies = lib.concatMapStringsSep "\n" (extLib:
      let
        libInfo = externalLibs.${extLib.name} or null;
      in if libInfo != null then ''
        echo "Copying flake-input library ${extLib.name}..."
        mkdir -p lib
        if [ -d "${libInfo}/lib" ]; then
          cp -r "${libInfo}/lib"/* lib/ 2>/dev/null || true
        fi
        if [ -f "${libInfo}" ]; then
          cp "${libInfo}" lib/ 2>/dev/null || true
        fi
      '' else if extLib ? vendor_path then ''
        echo "Staging vendor library ${extLib.name} from ${extLib.vendor_path}..."
        mkdir -p lib
        for f in "${src}/${extLib.vendor_path}"/lib*; do
          [ -f "$f" ] && cp "$f" lib/ || true
        done
      '' else ""
    ) config.external_libraries;

  in pkgs.stdenv.mkDerivation (commonArgs // {
    pname = "${commonArgs.pname}-lib";

    inherit src;

    preConfigure = ''
      runHook prePreConfigure

      # Create generated_code directory for generated files
      mkdir -p ./generated_code

      # Copy include files from module dependencies
      ${moduleDepIncludes}

      # Copy external libraries
      ${externalLibCopies}

      # Run logos-cpp-generator with metadata.json (present in src) and --general-only flag
      echo "Running logos-cpp-generator..."
      logos-cpp-generator --metadata metadata.json --general-only --output-dir ./generated_code

      # Check what was generated by logos-cpp-generator
      echo "Checking generated files in generated_code:"
      ls -la ./generated_code/ 2>/dev/null || echo "No generated files"

      # Create include directory and organize generated files
      if [ -f "./generated_code/core_manager_api.h" ] || [ -f "./generated_code/logos_sdk.h" ]; then
        echo "Creating include directory and moving generated files..."
        mkdir -p ./generated_code/include
        # Move generated header files to include directory
        for file in ./generated_code/*.h; do
          if [ -f "$file" ]; then
            mv "$file" ./generated_code/include/
          fi
        done
        # Also copy generated .cpp files to include directory
        for file in ./generated_code/*.cpp; do
          if [ -f "$file" ]; then
            cp "$file" ./generated_code/include/
          fi
        done
        echo "Generated include directory:"
        ls -la ./generated_code/include/ 2>/dev/null || echo "No include files"
      fi

      # Run any custom preConfigure hook
      ${preConfigure}

      runHook postPreConfigure
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p $out/lib

      # Find and copy the built plugin library
      if [ -f modules/${config.name}_plugin.dylib ]; then
        cp modules/${config.name}_plugin.dylib $out/lib/
      elif [ -f modules/${config.name}_plugin.so ]; then
        cp modules/${config.name}_plugin.so $out/lib/
      elif [ -f ${config.name}_plugin.dylib ]; then
        cp ${config.name}_plugin.dylib $out/lib/
      elif [ -f ${config.name}_plugin.so ]; then
        cp ${config.name}_plugin.so $out/lib/
      else
        echo "Error: No plugin library file found"
        echo "Searching for any plugin files..."
        find . -name "*_plugin.*" -type f 2>/dev/null || true
        exit 1
      fi

      # Copy any external libraries from build directory (platform-specific only)
      echo "Platform library extension: ${libExt}"
      if [ -d lib ]; then
        echo "Checking build lib/ directory..."
        for libfile in lib/*; do
          if [ -f "$libfile" ] && [[ "$libfile" == *.${libExt} ]]; then
            echo "Copying build library: $(basename $libfile)"
            cp "$libfile" $out/lib/
          fi
        done
      fi

      # Copy external libraries from source lib/ directory (platform-specific only)
      if [ -d "${src}/lib" ]; then
        echo "Checking source lib/ directory..."
        for libfile in "${src}"/lib/*; do
          if [ -f "$libfile" ] && [[ "$libfile" == *.${libExt} ]]; then
            basename_file=$(basename "$libfile")
            echo "Copying source library: $basename_file"
            cp "$libfile" $out/lib/
          fi
        done
      fi

      # Fix library paths on macOS
      ${lib.optionalString pkgs.stdenv.hostPlatform.isDarwin ''
        # Fix install name for the plugin
        if [ -f "$out/lib/${config.name}_plugin.dylib" ]; then
          ${pkgs.darwin.cctools}/bin/install_name_tool -id "@rpath/${config.name}_plugin.dylib" "$out/lib/${config.name}_plugin.dylib"
        fi

        # Fix install_name for all external libraries
        for dylib in $out/lib/*.dylib; do
          if [ -f "$dylib" ]; then
            libname=$(basename "$dylib")
            ${pkgs.darwin.cctools}/bin/install_name_tool -id "@rpath/$libname" "$dylib" 2>/dev/null || true
          fi
        done

        # Fix references to external libraries in the plugin.
        # Libraries may be referenced by bare name (e.g. "libcalc.dylib") or
        # by absolute build/nix-store paths. Rewrite any reference whose
        # basename matches a library shipped in $out/lib/ to @rpath/<name>.
        for plugin in $out/lib/*_plugin.dylib; do
          if [ -f "$plugin" ]; then
            PLUGIN_NAME=$(basename "$plugin")
            for libfile in $out/lib/*.dylib; do
              LIBNAME=$(basename "$libfile")
              [ "$LIBNAME" = "$PLUGIN_NAME" ] && continue
              # Fix bare-name reference (e.g. "libcalc.dylib" -> "@rpath/libcalc.dylib")
              ${pkgs.darwin.cctools}/bin/install_name_tool -change "$LIBNAME" "@rpath/$LIBNAME" "$plugin" 2>/dev/null || true
              # Fix any absolute-path reference ending with this library name
              ${pkgs.darwin.cctools}/bin/otool -L "$plugin" | awk "{print \$1}" | grep "/$LIBNAME" | while read OLD_REF; do
                echo "Fixing reference: $OLD_REF -> @rpath/$LIBNAME"
                ${pkgs.darwin.cctools}/bin/install_name_tool -change "$OLD_REF" "@rpath/$LIBNAME" "$plugin" 2>/dev/null || true
              done
            done
          fi
        done
      ''}

      # Install generated include files
      if [ -d "./generated_code/include" ]; then
        mkdir -p $out/include
        cp -r ./generated_code/include/* $out/include/
        echo "Installed generated include files:"
        ls -la $out/include/ 2>/dev/null || echo "No files"
      fi

      # Run any custom postInstall hook
      ${postInstall}

      runHook postInstall
    '';
  });
}
