#include "lidl_gen_cdylib_glue.h"
#include "lidl_emit_common.h"

#include <QStringList>
#include <QTextStream>

QString lidlMakeCdylibGlueHeader(const ModuleDecl& module, bool multi)
{
    const QString className = lidlToPascalCase(qs(module.name));
    QString c;
    QTextStream s(&c);

    s << "// AUTO-GENERATED by logos-qt-host-generator --backend cdylib -- do not edit\n";
    s << "//\n";
    s << "// The UNIFORM Qt-plugin glue over the common module-impl C ABI\n";
    s << "// (logos_module_impl.h). Identical regardless of the module's source\n";
    s << "// language (C++ or Rust): it only knows the C symbols, which are\n";
    s << "// linked in from the module's cdylib. logos_host loads it unchanged.\n";
    s << "#pragma once\n\n";
    s << "#include \"interface.h\"\n";
    s << "#include \"logos_api.h\"\n";
    s << "#include \"logos_provider_object.h\"\n";
    s << "#include \"logos_json_convert.h\"\n";
    s << "#include \"logos_module_impl.h\"\n";
    // Needed for LOGOS_PROTOCOL_VERSION_MINOR, which the host-services guard in
    // onInit tests. Without it the macro is simply undefined here and the guard
    // silently evaluates FALSE — the grant is never forwarded and the module
    // comes up unprivileged with no diagnostic anywhere.
    s << "#include \"logos_protocol.h\"\n";
    s << "#include \"logos_types.h\"\n";
    s << "#include <QDebug>\n";
    s << "#include <QObject>\n";
    s << "#include <QJsonArray>\n";
    s << "#include <QJsonDocument>\n";
    s << "#include <QSet>\n";
    s << "#include <QString>\n";
    s << "#include <QVariant>\n";
    s << "#include <QVariantList>\n";
    if (multi) {
        // concurrency:"multi" defers behind the ordinary callMethod: a worker
        // runs the handler and the result is pushed back as a completion event
        // (logos_async_dispatch.h) — no new provider/host vtable method.
        s << "#include \"logos_async_dispatch.h\"\n";
        s << "#include <QVariantMap>\n";
        s << "#include <atomic>\n";
        s << "#include <cstdint>\n";
        s << "#include <QThread>\n";
    }
    s << "#include <nlohmann/json.hpp>\n\n";

    // LogosProviderBase (not the bare interface): its informModuleToken saves
    // into the HOST-stack TokenManager — what ModuleProxy validates INBOUND
    // calls against — exactly as QtProviderObject does for a legacy
    // Q_INVOKABLE plugin (and as the retired hand-written
    // `interface: "provider"` modules used to). The glue then ALSO forwards
    // every token across the C ABI for the cdylib's own stack.
    s << "class " << className << "CdylibProvider : public LogosProviderBase {\n";
    s << "public:\n";
    if (multi) {
        s << "    // concurrency:\"multi\": callMethod does NOT block — it hands the call to a\n";
        s << "    // worker and returns a pending sentinel at once, then the worker pushes the\n";
        s << "    // result back as a completion event. This is the SAME callMethod slot every\n";
        s << "    // provider has — there is no extra provider/host vtable method, so the\n";
        s << "    // provider ABI is unchanged and an old host loads + forwards this module.\n";
    }
    s << "    QVariant callMethod(const QString& methodName, const QVariantList& args) override;\n";
    s << "    QJsonArray getMethods() override;\n";
    s << "    bool informModuleToken(const QString& moduleName, const QString& token) override;\n";
    s << "    void setEventListener(EventCallback callback) override;\n";
    s << "    QString providerName() const override { return QStringLiteral(\"" << module.name << "\"); }\n";
    s << "    QString providerVersion() const override { return QStringLiteral(\"" << (module.version.empty() ? QStringLiteral("1.0.0") : qs(module.version)) << "\"); }\n";
    s << "protected:\n";
    s << "    void onInit(LogosAPI* api) override;\n";
    s << "private:\n";
    s << "    EventCallback m_eventCallback;\n";
    s << "    static void emitTrampoline(const char* eventName, const char* dataJson, void* userData);\n";
    if (multi)
        s << "    std::atomic<std::uint64_t> m_callCounter{0};  // unique deferred-call ids\n";
    s << "};\n\n";

    // The root plugin must also implement PluginInterface — logos_host's
    // module_initializer hard-requires it before any provider detection.
    s << "class " << className << "CdylibPlugin : public QObject, public PluginInterface, public LogosProviderPlugin {\n";
    s << "    Q_OBJECT\n";
    s << "    Q_PLUGIN_METADATA(IID LogosProviderPlugin_iid FILE \"metadata.json\")\n";
    s << "    Q_INTERFACES(PluginInterface LogosProviderPlugin)\n";
    s << "public:\n";
    s << "    QString name() const override { return QStringLiteral(\"" << module.name << "\"); }\n";
    s << "    QString version() const override { return QStringLiteral(\"" << (module.version.empty() ? QStringLiteral("1.0.0") : qs(module.version)) << "\"); }\n";
    // Teardown, reached by the host through the META-OBJECT rather than the
    // vtable. PluginInterface is compiled separately into every module .so, so
    // adding a virtual there would shift the vtable under every plugin already
    // built; a plugin without this hook must be a no-op, not undefined
    // behaviour. `initLogos` is delivered by name for the same reason.
    //
    // Returns the LogosShutdown as an int because the host resolves this by
    // signature string and must not need the SDK enum to do it.
    s << "    Q_INVOKABLE int aboutToUnload();\n";
    s << "Q_SIGNALS:\n";
    s << "    // Emitted when an Asynchronous teardown has finished. The host\n";
    s << "    // connects to this by name and stops waiting on the first one.\n";
    s << "    void unloadFinished();\n";
    s << "public:\n";
    s << "    LogosProviderObject* createProviderObject() override {\n";
    s << "        return new " << className << "CdylibProvider();\n";
    s << "    }\n";
    s << "};\n";
    return c;
}

QString lidlMakeCdylibGlueSource(const ModuleDecl& module, bool multi)
{
    const QString className = lidlToPascalCase(qs(module.name));
    const QString provider = className + "CdylibProvider";
    const QString plugin = className + "CdylibPlugin";

    // Which methods return StdLogosResult — the glue re-materializes the Qt
    // LogosResult QVariant callers expect on the wire.
    QStringList resultMethods;
    for (const MethodDecl& md : module.methods)
        if (md.resultReturn) resultMethods << qs(md.name);

    // Which methods return `void`. Derived from the shared contract, so every
    // cdylib backend converges here regardless of the language behind the C ABI.
    //
    // `void` is not a LIDL builtin — it parses as Named("void") — and the
    // backends handled that Named differently: the C++ cdylib has an arm that
    // returns "true", the Rust one falls to its catch-all and returns JSON null.
    // Null is the failure token further up (logos_json_convert turns it into an
    // invalid QVariant, which core_service reports as METHOD_FAILED), so the same
    // void method answered `true` from one provider and "the call failed" from
    // the other, on a contract they share.
    QStringList voidMethods;
    for (const MethodDecl& md : module.methods)
        if (!md.resultReturn && md.returnType.name == "void") voidMethods << qs(md.name);

    // The protocol-0.6 guard, spelled once and emitted at four sites (the push
    // and the pop, in each of the two concurrency branches). MAJOR-aware and
    // written EXPANDED, for the two reasons logos_protocol.h gives: a bare
    // `MINOR >= 6` goes false at 1.0.0 and takes this call and the backend's
    // definition of the symbol away TOGETHER — everything still builds and
    // loads, and modules silently stop being able to name their caller — and
    // unifdef, which resolves these conditionals in the backends' ABI checks,
    // handles nested integer arithmetic but no-ops on a function-like macro.
    const QString callerGuard =
        QStringLiteral("#if defined(LOGOS_PROTOCOL_VERSION_MINOR) && "
                       "(LOGOS_PROTOCOL_VERSION_MAJOR > 0 || "
                       "(LOGOS_PROTOCOL_VERSION_MAJOR == 0 && "
                       "LOGOS_PROTOCOL_VERSION_MINOR >= 6))\n");

    QString c;
    QTextStream s(&c);
    s << "// AUTO-GENERATED by logos-qt-host-generator --backend cdylib -- do not edit\n";
    s << "#include \"" << module.name << "_cdylib_glue.h\"\n\n";

    if (!multi) {
        s << "QVariant " << provider << "::callMethod(const QString& methodName, const QVariantList& args)\n{\n";
        s << "    nlohmann::json jArgs = nlohmann::json::array();\n";
        s << "    for (const QVariant& a : args)\n";
        s << "        jArgs.push_back(logos::qvariantToNlohmann(a));\n";
        s << "    const std::string dumped = jArgs.dump();\n";
        // WHO IS CALLING, pushed across the C ABI around exactly one dispatch.
        //
        // The pull is a call into the HOST image, not a read of anything here:
        // this glue is compiled into the module plugin, which links its own copy
        // of LogosAPI and of the protocol's caller thread-local, and a direct
        // read finds a slot no CallerScope ever wrote (empty forever on macOS
        // and Windows; correct on Linux, which is what makes it invisible).
        // LogosProviderBase::currentCallerJson() is that call, and the base
        // class owns the invokeMethod incantation so this emitter never repeats
        // it.
        s << callerGuard;
        s << "    // WHO IS CALLING, for this dispatch and no other. Pulled OUT of the\n";
        s << "    // host image by name; a direct read here would find this plugin's own\n";
        s << "    // copy of the thread-local, which nothing ever writes.\n";
        s << "    const std::string callerJson = currentCallerJson();\n";
        s << "    logos_module_set_call_caller(callerJson.c_str());\n";
        s << "#endif\n";
        s << "    char* result = logos_module_dispatch(methodName.toUtf8().constData(), dumped.c_str());\n";
        // Popped IMMEDIATELY after the dispatch and before the first early
        // return below, so no path out of this function leaves the caller
        // standing. (NULL is the pop on this ABI, not a weaker identity.) A
        // dispatch that unwound would still leak the frame; the module-impl C
        // ABI forbids that, and both backends catch, so this stays a straight
        // line rather than an RAII type emitted into every glue file.
        s << callerGuard;
        s << "    logos_module_set_call_caller(nullptr);\n";
        s << "#endif\n";
        s << "    if (!result) return QVariant();\n";
        s << "    nlohmann::json jResult = nlohmann::json::parse(result, nullptr, false);\n";
        s << "    logos_module_string_free(result);\n";
        s << "    if (jResult.is_discarded()) return QVariant();\n";
        if (!voidMethods.isEmpty()) {
            s << "    // `void` methods answer QVariant(true) whatever the cdylib put on the\n";
            s << "    // C ABI. An invalid QVariant is this slot's failure token, so a void\n";
            s << "    // method needs SOME value to mean \"it ran\".\n";
            s << "    static const QSet<QString> kVoidMethods = {";
            for (int i = 0; i < voidMethods.size(); ++i) {
                s << "QStringLiteral(\"" << voidMethods[i] << "\")";
                if (i + 1 < voidMethods.size()) s << ", ";
            }
            s << "};\n";
            s << "    if (kVoidMethods.contains(methodName)) return QVariant(true);\n";
        }
        if (!resultMethods.isEmpty()) {
            s << "    // StdLogosResult-returning methods: re-materialize the Qt LogosResult\n";
            s << "    // QVariant the wire expects ({success, value, error} crossed the C ABI).\n";
            s << "    static const QSet<QString> kResultMethods = {";
            for (int i = 0; i < resultMethods.size(); ++i) {
                s << "QStringLiteral(\"" << resultMethods[i] << "\")";
                if (i + 1 < resultMethods.size()) s << ", ";
            }
            s << "};\n";
            s << "    if (kResultMethods.contains(methodName) && jResult.is_object()) {\n";
            s << "        LogosResult lr;\n";
            s << "        lr.success = jResult.value(\"success\", false);\n";
            s << "        lr.value = logos::nlohmannToQVariant(jResult.value(\"value\", nlohmann::json()));\n";
            s << "        lr.error = jResult.contains(\"error\") && jResult[\"error\"].is_string()\n";
            s << "            ? QVariant(QString::fromStdString(jResult[\"error\"].get<std::string>()))\n";
            s << "            : QVariant();\n";
            s << "        return QVariant::fromValue(lr);\n";
            s << "    }\n";
        }
        s << "    return logos::nlohmannToQVariant(jResult);\n";
        s << "}\n\n";
    } else {
        // concurrency:"multi": callMethod does NOT block. Marshal the args, hand
        // the call to a worker thread (the cdylib's logos_module_dispatch is
        // thread-safe in multi mode), and return a PENDING SENTINEL immediately so
        // the dispatch thread is freed for other callers. When the worker
        // finishes it pushes the result back as a completion event keyed by
        // callId, over the provider's existing event listener; the consumer
        // transport awaits it. This rides the ORDINARY callMethod slot — there is
        // no new provider/host vtable method, so the provider ABI is unchanged and
        // an old host loads + forwards this module unmodified.
        s << "QVariant " << provider << "::callMethod(const QString& methodName, const QVariantList& args)\n{\n";
        s << "    nlohmann::json jArgs = nlohmann::json::array();\n";
        s << "    for (const QVariant& a : args)\n";
        s << "        jArgs.push_back(logos::qvariantToNlohmann(a));\n";
        s << "    const std::string dumped = jArgs.dump();\n";
        s << "    const std::string method = methodName.toStdString();\n";
        if (!resultMethods.isEmpty()) {
            s << "    static const QSet<QString> kResultMethods = {";
            for (int i = 0; i < resultMethods.size(); ++i) {
                s << "QStringLiteral(\"" << resultMethods[i] << "\")";
                if (i + 1 < resultMethods.size()) s << ", ";
            }
            s << "};\n";
            s << "    const bool isResultMethod = kResultMethods.contains(methodName);\n";
        }
        if (!voidMethods.isEmpty()) {
            s << "    static const QSet<QString> kVoidMethods = {";
            for (int i = 0; i < voidMethods.size(); ++i) {
                s << "QStringLiteral(\"" << voidMethods[i] << "\")";
                if (i + 1 < voidMethods.size()) s << ", ";
            }
            s << "};\n";
            s << "    const bool isVoidMethod = kVoidMethods.contains(methodName);\n";
        }
        s << "    const QString callId = QStringLiteral(\"lc-%1\").arg(\n";
        s << "        static_cast<qulonglong>(m_callCounter.fetch_add(1, std::memory_order_relaxed)));\n";
        s << "    EventCallback eventCb = m_eventCallback;  // copied for the worker\n";
        // THE PULL IS HERE, ON THE DISPATCH THREAD, and this placement is the
        // entire correctness of the multi branch.
        //
        // callMethod is still ENTERED on the thread ModuleProxy delivered the
        // call on, which is the thread whose CallerScope is open and whose
        // thread-local holds the document. The worker below is a brand-new
        // QThread: it has no scope, never had one, and cannot acquire one. So
        // the document is captured here, by value, as one more of the worker's
        // captured values — exactly as `method`, `dumped` and `callId` are.
        //
        // Written the other way round — pulling inside the worker lambda — this
        // ALSO COMPILES, and every handler reads Unknown on every platform. It
        // passes any test that only ever has one caller, and it is
        // indistinguishable from a legacy plugin or a background thread, both of
        // which read Unknown legitimately. It is emitted unguarded because
        // currentCallerJson() is declared unconditionally by
        // LogosProviderBase (only its body is version-gated), which keeps the
        // capture list one line and the ordering unambiguous.
        s << "    // ON THE DISPATCH THREAD, deliberately: this is the thread whose\n";
        s << "    // CallerScope is open. The worker below has none and never will, so a\n";
        s << "    // pull made in there answers Unknown on every platform -- and compiles.\n";
        s << "    const std::string callerJson = currentCallerJson();\n";
        // Run the handler on a real QThread, not a raw std::thread: if the handler
        // makes an outbound module->module call it spins nested QEventLoops (to
        // acquire the QtRO replica and await a deferred reply), and only a genuine
        // QThread carries a Qt event dispatcher that can drive those — an adopted
        // std::thread cannot pump the QtRO socket, so such calls would hang. The
        // client stays owned by this worker (inline, no cross-thread marshaling).
        // Built from the same two conditions that decide whether the locals
        // exist at all, rather than hand-written per case. There are FOUR
        // combinations of (has void methods, has result methods) and only two
        // hand-written lists, so `void && !result` captured neither flag and
        // named `isVoidMethod` in the body regardless — a module with a void
        // method and no LogosResult method did not compile under
        // concurrency:"multi". A capture-default is deliberately still not used:
        // this lambda outlives the frame, so every capture has to be by value on
        // purpose.
        //
        // `callerJson` is captured UNCONDITIONALLY even though only the guarded
        // push reads it, so the capture list stays ONE LINE. Both this suite and
        // tests/test-qt-host-generator.nix read that list with
        // `grep -o 'QThread::create(\[[^]]*\]'`, which cannot span lines, and a
        // preprocessor conditional inside the brackets would take the list off
        // the single line those greps depend on. The #else below spends the
        // capture instead, so no compiler warns about it below protocol 0.6.
        QString workerCaptures = "method, dumped";
        if (!voidMethods.isEmpty())   workerCaptures += ", isVoidMethod";
        if (!resultMethods.isEmpty()) workerCaptures += ", isResultMethod";
        workerCaptures += ", callId, eventCb, callerJson";
        s << "    QThread* worker = QThread::create([" << workerCaptures << "]() {\n";
        // The push/dispatch/pop triple moves VERBATIM into the worker: the
        // module image's caller store is per-thread too, so the thread that
        // runs the handler is the thread that has to be told.
        s << callerGuard;
        s << "        logos_module_set_call_caller(callerJson.c_str());\n";
        s << "#else\n";
        s << "        (void)callerJson;  // no caller surface below protocol 0.6\n";
        s << "#endif\n";
        s << "        char* result = logos_module_dispatch(method.c_str(), dumped.c_str());\n";
        s << callerGuard;
        s << "        logos_module_set_call_caller(nullptr);\n";
        s << "#endif\n";
        s << "        QVariant value;\n";
        s << "        if (result) {\n";
        s << "            nlohmann::json jResult = nlohmann::json::parse(result, nullptr, false);\n";
        s << "            logos_module_string_free(result);\n";
        s << "            if (!jResult.is_discarded()) {\n";
        if (!voidMethods.isEmpty()) {
            s << "                if (isVoidMethod) {\n";
            s << "                    value = QVariant(true);\n";
            s << "                } else\n";
        }
        if (!resultMethods.isEmpty()) {
            s << "                if (isResultMethod && jResult.is_object()) {\n";
            s << "                    LogosResult lr;\n";
            s << "                    lr.success = jResult.value(\"success\", false);\n";
            s << "                    lr.value = logos::nlohmannToQVariant(jResult.value(\"value\", nlohmann::json()));\n";
            s << "                    lr.error = jResult.contains(\"error\") && jResult[\"error\"].is_string()\n";
            s << "                        ? QVariant(QString::fromStdString(jResult[\"error\"].get<std::string>()))\n";
            s << "                        : QVariant();\n";
            s << "                    value = QVariant::fromValue(lr);\n";
            s << "                } else {\n";
            s << "                    value = logos::nlohmannToQVariant(jResult);\n";
            s << "                }\n";
        } else {
            s << "                { value = logos::nlohmannToQVariant(jResult); }\n";
        }
        s << "            }\n";
        s << "        }\n";
        s << "        if (eventCb)\n";
        s << "            eventCb(logos::callCompleteEvent(), QVariantList{ callId, value });\n";
        s << "    });\n";
        s << "    QObject::connect(worker, &QThread::finished, worker, &QThread::deleteLater);\n";
        s << "    worker->start();\n";
        s << "    QVariantMap pending;\n";
        s << "    pending[logos::pendingCallKey()] = callId;\n";
        s << "    return pending;\n";
        s << "}\n\n";
    }

    s << "QJsonArray " << provider << "::getMethods()\n{\n";
    s << "    char* json = logos_module_get_methods();\n";
    s << "    if (!json) return QJsonArray();\n";
    s << "    QJsonDocument doc = QJsonDocument::fromJson(QByteArray(json));\n";
    s << "    logos_module_string_free(json);\n";
    s << "    return doc.isArray() ? doc.array() : QJsonArray();\n";
    s << "}\n\n";

    s << "bool " << provider << "::informModuleToken(const QString& moduleName, const QString& token)\n{\n";
    s << "    // Host-stack save first: ModuleProxy validates INBOUND calls against\n";
    s << "    // the host's TokenManager (LogosProviderBase saves there).\n";
    s << "    const bool hostOk = LogosProviderBase::informModuleToken(moduleName, token);\n";
    s << "    // Then forward across the C ABI: the cdylib's own protocol stack\n";
    s << "    // (a separate static copy) authenticates the module's OUTBOUND calls.\n";
    s << "    const bool implOk = logos_module_accept_token(moduleName.toUtf8().constData(),\n";
    s << "                                                  token.toUtf8().constData()) == 0;\n";
    s << "    return hostOk && implOk;\n";
    s << "}\n\n";

    s << "void " << provider << "::setEventListener(EventCallback callback)\n{\n";
    s << "    m_eventCallback = std::move(callback);\n";
    s << "    logos_module_set_emit_callback(&" << provider << "::emitTrampoline, this);\n";
    s << "}\n\n";

    s << "void " << provider << "::emitTrampoline(const char* eventName, const char* dataJson, void* userData)\n{\n";
    s << "    auto* self = static_cast<" << provider << "*>(userData);\n";
    s << "    if (!self || !self->m_eventCallback || !eventName) return;\n";
    s << "    nlohmann::json payload = dataJson\n";
    s << "        ? nlohmann::json::parse(dataJson, nullptr, false)\n";
    s << "        : nlohmann::json::array();\n";
    s << "    if (payload.is_discarded() || !payload.is_array()) payload = nlohmann::json::array();\n";
    s << "    self->m_eventCallback(QString::fromUtf8(eventName),\n";
    s << "                          logos::nlohmannArgsToQVariantList(payload));\n";
    s << "}\n\n";

    s << "void " << provider << "::onInit(LogosAPI* api)\n{\n";
    s << "    QObject* obj = api;\n";
    s << "    if (!obj) return;\n";
    s << "    // Token FIRST: the cdylib runs its own protocol stack (a separate\n";
    s << "    // static copy with its own TokenManager). Seed it with the\n";
    s << "    // host-issued auth token the initializer surfaces as a property\n";
    s << "    // (set before registerObject, so it is visible here), under the\n";
    s << "    // same keys the initializer uses (\"core\" / \"capability_module\")\n";
    s << "    // — this authenticates the module's OUTBOUND calls (incl. the\n";
    s << "    // capability requestModule flow). Seeding before the context\n";
    s << "    // forward means on_context_ready/onContextReady can already make\n";
    s << "    // authenticated calls whenever the impl's ready-latch fires.\n";
    s << "    const QString authToken = obj->property(\"authToken\").toString();\n";
    s << "    if (!authToken.isEmpty()) {\n";
    s << "        logos_module_accept_token(\"core\", authToken.toUtf8().constData());\n";
    s << "        logos_module_accept_token(\"capability_module\", authToken.toUtf8().constData());\n";
    s << "    }\n";
    s << "    // Host services next, by the same property-stamping channel: the\n";
    s << "    // host decides which modules are privileged and stamps a JSON\n";
    s << "    // array (from the closed set logos-protocol documents) on the\n";
    s << "    // LogosAPI object; an ordinary module simply has no such property\n";
    s << "    // and stays fail-closed.\n";
    s << "    //\n";
    s << "    // This has to cross the C ABI rather than being recorded by the\n";
    s << "    // host: the host binary and this cdylib each link their own copy\n";
    s << "    // of logos-protocol, so each has its own process-global grant\n";
    s << "    // state, exactly as each has its own TokenManager (which is why\n";
    s << "    // the token above is re-seeded here too). A grant the host\n";
    s << "    // records for itself would leave this module's gates shut, and\n";
    s << "    // silently: lp_token_keys() would just keep returning null.\n";
    s << "    //\n";
    s << "    // BEFORE the context forward, so a privileged impl may already\n";
    s << "    // use the granted services from its context-ready hook.\n";
    // Same protocol-MINOR guard as the C-ABI export: glue generated for a
    // module built against logos-protocol < 0.3 must still compile, and there
    // is no grant entry point to call there.
    s << "#if defined(LOGOS_PROTOCOL_VERSION_MINOR) && "
         "(LOGOS_PROTOCOL_VERSION_MAJOR > 0 || "
         "(LOGOS_PROTOCOL_VERSION_MAJOR == 0 && "
         "LOGOS_PROTOCOL_VERSION_MINOR >= 3))\n";
    s << "    const QString hostServices = obj->property(\"hostServices\").toString();\n";
    s << "    if (!hostServices.isEmpty()) {\n";
    s << "        if (logos_module_grant_host_services(\n";
    s << "                hostServices.toUtf8().constData()) != 0) {\n";
    s << "            // Refused wholesale (malformed, or an unrecognised name).\n";
    s << "            // Say so: the module keeps running UNPRIVILEGED, and the\n";
    s << "            // failure would otherwise surface far away as an\n";
    s << "            // unexplained empty token registry.\n";
    s << "            qWarning() << \"[" << module.name << "] host services refused:\"\n";
    s << "                       << hostServices;\n";
    s << "        }\n";
    s << "    }\n";
    s << "#endif\n";
    s << "    // Context LAST — comes from the host's property stamping on the\n";
    s << "    // LogosAPI object, forwarded across the C ABI; the cdylib never\n";
    s << "    // sees Qt. (The impl fires its context-ready hook once BOTH the\n";
    s << "    // context and the emit callback have been delivered.)\n";
    s << "    logos_module_set_context(\n";
    s << "        obj->property(\"modulePath\").toString().toUtf8().constData(),\n";
    s << "        obj->property(\"instanceId\").toString().toUtf8().constData(),\n";
    s << "        obj->property(\"instancePersistencePath\").toString().toUtf8().constData());\n";
    s << "}\n\n";

    // Teardown. The plugin object is what the host reaches by name; the work
    // itself lives behind the C ABI, in the module's own language.
    s << "int " << plugin << "::aboutToUnload()\n{\n";
    // The DECLARATION stays unguarded: moc emits a call to it, so guarding it
    // away would be an undefined symbol at link, and the host's by-name lookup
    // should find the same meta-object surface on every module. Only the BODY
    // depends on the protocol -- on anything older than 0.5 the two C ABI
    // symbols do not exist, and answering 0 (Synchronous) is exactly right: a
    // module whose ABI cannot carry teardown has nothing to wait for.
    s << "#if defined(LOGOS_PROTOCOL_VERSION_MINOR) && "
         "(LOGOS_PROTOCOL_VERSION_MAJOR > 0 || "
         "(LOGOS_PROTOCOL_VERSION_MAJOR == 0 && "
         "LOGOS_PROTOCOL_VERSION_MINOR >= 5))\n";
    // Installed BEFORE asking, because a module that finishes inline would
    // otherwise signal into an empty slot and the host would wait out the whole
    // grace period for a module already done.
    //
    // The trampoline runs on whichever thread the module finished on, so it
    // must not touch the plugin directly -- QMetaObject::invokeMethod with a
    // queued connection marshals the emission back to the plugin's thread,
    // which is where the host is waiting.
    s << "    logos_module_set_unload_done_callback(\n";
    s << "        [](void* userData) {\n";
    s << "            auto* self = static_cast<" << plugin << "*>(userData);\n";
    s << "            QMetaObject::invokeMethod(self, \"unloadFinished\", Qt::QueuedConnection);\n";
    s << "        }, this);\n";
    s << "    return logos_module_about_to_unload();\n";
    s << "#else\n";
    s << "    return 0;  // Synchronous: this protocol has no teardown surface\n";
    s << "#endif\n";
    s << "}\n";
    return c;
}
